[package]
name = "untitled2"
version = "0.1.0"
authors = ["Kofi Otuo <otuokofi@outlook.com>"]
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = { git = "https://github.com/rustwasm/wasm-bindgen.git" }

[profile.dev]
strip = true

[profile.release]
strip = true
